apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasaku-volume-claim
  labels:
    app: datasaku
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi