apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasaku-volume
  labels:
    type: local
    app: datasaku
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/datasaku