apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 80
      nodePort: 30200