apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-volume-claim
  labels:
    app: nessie
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi