apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
  namespace: spark-dev
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-dev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---